language: cpp
os:
- linux
compiler:
  - clang
  - gcc
  
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; fi
- if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
- if [ $TRAVIS_OS_NAME == osx ]; then curl http://www.cmake.org/files/v2.8/cmake-2.8.12.2-Darwin64-universal.tar.gz -o cmake.tar.gz; fi
- if [ $TRAVIS_OS_NAME == osx ]; then tar xzf cmake.tar.gz; fi
- if [ $TRAVIS_OS_NAME == osx ]; then export PATH=$PATH:"cmake-2.8.12.2-Darwin64-universal/CMake 2.8-12.app/Contents/bin"; fi
- git submodule update --init
install:
 # clang 3.4
 - if [ "$CXX" == "clang++" ]; then export CPP_ASSERT_DIR=`pwd`; fi
 - if [ "$CXX" == "clang++" ]; then echo "CPP_ASSERT_DIR=${CPP_ASSERT_DIR}"; fi
 - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
 - if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-std=c++0x -stdlib=libc++"; fi
 - if [ "$CXX" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi
 - if [ "$CXX" == "clang++" ]; then cd libcxx/lib && bash buildit; fi
 - if [ "$CXX" == "clang++" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
 - if [ "$CXX" == "clang++" ]; then sudo mkdir /usr/include/c++/v1; fi
 - if [ "$CXX" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
 - if [ "$CXX" == "clang++" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
 - if [ "$CXX" == "clang++" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi 
 - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4" CC="clang-3.4"; fi
 - if [ "$CXX" == "clang++" ]; then cd $CPP_ASSERT_DIR; fi
env:
- BUILD_TYPE=Debug
- BUILD_TYPE=Release
- BUILD_TYPE=Test
script:
- pwd
- ls -alh
- cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE - .
- make 
- make test
after_failure:
- cat Testing/Temporary/LastTest.log