version: 0.1.{build}

branches:
    # whitelist
    only:
        - master

os:
    - Visual Studio 2015 RC
    - Windows Server 2012 R2
init:
    - git config --global core.autocrlf input
# clone directory
clone_folder: c:\projects\cppassert
platform: 
    - x86
    - x64
configuration: Debug
install:
# by default, all script lines are interpreted as batch
build:
  project: ALL_BUILD.vcxproj
  parallel: false
  verbosity: normal
# scripts to run before build
before_build:
    - set
    - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    - echo Running cmake...
    - cd c:\projects\cppassert
    - cmake -H. --config Debug .
    - dir *
test_script:
  - echo %CD%
  - ctest -VV


