version: 0.1.{build}

environment:
    matrix:
    - platform: x64
      msvs_toolset: 12
      cmake_generator_name: Visual Studio 12 Win64
      architecture: amd64
    - platform: x86
      msvs_toolset: 12
      cmake_generator_name: Visual Studio 12
      architecture: amd64_x86
    - platform: x64
      msvs_toolset: 14 
      cmake_generator_name: Visual Studio 14 Win64
      architecture: amd64
    - platform: x86
      msvs_toolset: 14
      cmake_generator_name: Visual Studio 14
      architecture: amd64_x86
      
matrix:
  fast_finish: true
  
branches:
    # whitelist
    only:
        - master

os:
    - Visual Studio 2015
init:
    - git config --global core.autocrlf input
# clone directory
clone_folder: c:\projects\cppassert

configuration: Debug
install:
# by default, all script lines are interpreted as batch
build:
  project: ALL_BUILD.vcxproj
  parallel: false
  verbosity: normal
# scripts to run before build
before_build:
    - cmd: set    
    - cmd: set PATH=C:\Program Files (x86)\MSBuild\%msvs_toolset%.0\bin;%PATH%
    - cmd: set PATH=C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\bin;%PATH%
    - cmd: CALL "C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\vcvarsall.bat" %architecture%
    - cmd: echo Running cmake...
    - cmd: cd c:\projects\cppassert
    - cmd: md build
    - cmd: cd build
    - cmd: echo %CMAKE_GENERATOR_NAME%
    - cmd: echo %platform%
    - cmd: echo %msvs_toolset%
    - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -H. --config Debug ..
    - cmd: dir *
test_script:
  - echo %CD%
  - ctest -VV


