version: 0.1.{build}

environment:
    matrix:
    - platform: x64
      msvs_toolset: 12
    - platform: x86
      msvs_toolset: 12
    - platform: x64
      msvs_toolset: 14      
    - platform: x86
      msvs_toolset: 14      

branches:
    # whitelist
    only:
        - master

os:
    - Visual Studio 2015
init:
    - git config --global core.autocrlf input
# clone directory
clone_folder: c:\projects\cppassert

configuration: Debug
install:
# by default, all script lines are interpreted as batch
build:
  project: ALL_BUILD.vcxproj
  parallel: false
  verbosity: normal
# scripts to run before build
before_build:
    - cmd: set PATH=C:\Program Files (x86)\MSBuild\%msvs_toolset%.0\bin;%PATH%
    - cmd: set PATH=C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\bin;%PATH%
    - cmd: if %platform% == x64 CALL "C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\vcvarsall.bat" amd64
    - cmd: if %platform% == x86 CALL "C:\Program Files (x86)\Microsoft Visual Studio %msvs_toolset%.0\VC\vcvarsall.bat" amd64_x86
    - cmd: echo Running cmake...
    - cmd: cd c:\projects\cppassert
    - cmd: if %platform% == x86 set CMAKE_GENERATOR_NAME="Visual Studio %msvs_toolset%"
    - cmd: if %platform% == x64 set CMAKE_GENERATOR_NAME="Visual Studio %msvs_toolset% Win64"
    - cmd: echo "CMAKE_GENERATOR_NAME: %CMAKE_GENERATOR_NAME%" %CMAKE_GENERATOR_NAME%
    - cmd: echo "msvs_toolset: %msvs_toolset%" %msvs_toolset%
    - cmd: echo "Platfform: %platform%" %platform%
    - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -H. --config Debug .
    - cmd: dir *
test_script:
  - echo %CD%
  - ctest -VV


