version: 0.1.{build}

branches:
    # whitelist
    only:
        - master

os:
    - Visual Studio 2014 CTP4
    - Visual Studio 2015 Preview
init:
    - git config --global core.autocrlf input
# clone directory
clone_folder: c:\projects\cppassert
platform: x86
configuration: Debug
install:
# by default, all script lines are interpreted as batch
build:
  project: ALL_BUILD.vcxproj
  parallel: true
  verbosity: normal
# scripts to run before build
before_build:    
    - echo Running cmake...
    - cd c:\projects\cppassert
    - cmake -H. --config Debug .
    - dir *
test_script:
  - echo %CD%
  - dir tests\*
  - dir tests\Release\*
  - dir tests\Debug\*
  - ctest -VV


